module.exports.INVALID_DATA_STATUS_CODE = 400;
module.exports.AUTH_ERROR_STATUS_CODE = 401;
module.exports.NOT_FOUND_STATUS_CODE = 404;
module.exports.SERVER_ERROR_STATUS_CODE = 500;
module.exports.DUPLICATE_ERROR_STATUS_CODE = 409;
